version: '3.3'

services:
  chatai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minichitchatai
    ports:
      - "3602:3000"
    environment:
      - NODE_ENV=production
      - GROQ_API_KEY=your_api_key_here
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - /app/.next